#!/usr/bin/env bash
# This script displays information about subdomains

# Define Variables
domain=$1
subdomain=$2

# List of subdomains
sd_list=("www" "lb-01" "web-01" "web-02")

# Define Function
dig_cmd() {
    subdomain=$2
    CMD=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')
    IP=$(echo "$CMD" | awk '{print $5}')
    RECORD=$(echo "$CMD" | awk '{print $4}')
    echo "The subdomain $subdomain is a $RECORD record and points to $IP"
}

if [ "$#" -eq 1 ]
then
    for sub in "${sd_list[@]}"
    do
        dig_cmd "$domain" "$sub"
    done
elif [ "$#" -eq 2 ]
then
    dig_cmd "$domain" "$subdomain"
fi
