#!/usr/bin/env bash
# This script installs a nginx on the web server

sudo apt-get update
sudo apt-get install nginx -y
sudo chown -R ubuntu /var/www 
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
