#!/usr/bin/env bash
# This script configures the Nginx server to have a custom 404 page that contains the string
# 'Ceci n'est pas une page'

ADD301_REDIRECT="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
ERRORPAGE_404="\\\terror_page 404 /error_404.html;"

sudo apt-get update
sudo apt-get install nginx -y
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sudo sed -i "32i $ERRORPAGE_404" /etc/nginx/sites-available/default
sudo sed -i "s|listen \[::\]:80 default_server;|listen \[::\]:80 default_server;\n\tadd_header X-Served-By \$hostname;|g" /etc/nginx/sites-available/default
sudo service nginx restart
