#!/usr/bin/env bash
# This script installs and configures HAproxy on the server

CONFIG="frontend http_front\n\tbind *:80\n\tdefault_backend http_back\n\nbackend http_back \
\n\tbalance roundrobin\n\tserver web-01 100.25.171.73:80 check\n\tserver web-02 54.210.174.198:80 check"

sudo apt-get update
sudo apt install -y haproxy
sudo sed -i "19i $CONFIG" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
