#!/usr/bin/env bash
# This generates a MySQL dump and creates a compressed archive out of it.

PASSWORD=$1

mysqldump -u root -p "$PASSWORD" --all-databases > backup.sql
tar -czf $(date +%d-%m-%Y).tar.gz backup.sql
