#!/usr/bin/env bash
# Displays 'Best School' 10 times and displays additional 'Hi' on the 9th iteration

count=1
while [ $count -le 10 ]
do
	# Check if the iterator is equal to 9
	if [ $count -eq 9 ];
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi

	# Increments the iterator
	((count++))
done
