#!/usr/bin/env bash
# Displays numbers from 1 to 20;
#	displays 4 and then 'bad luck from China' for the 4th iteration
#	displays 9 and then 'bad luck from Japan' for the 9th iteration
#	displays 17 and then 'bad luck from Italy' for the 17th iteration

count=1
while [ $count -le 20 ]
do
	case $count in
		4)
			echo "$count"
			echo "bad luck in China"
			;;
		8)
			echo "$count"
			echo "bad luck in Japan"
			;;
		17)
			echo "$count"
			echo "bad luck in Italy"
			;;
		*)
			echo "$count"
			;;
	esac

	((count++))
done
