#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes

hour=0
minutes=1
while [ $hour -le 12 ]
do
	echo "Hour: $hour"

	while [ $minutes -lt 60 ]
	do
		echo "$minutes"

		((minutes++))
	done

	((hour++))
	minutes=1
done			
