#!/usr/bin/env bash
# This script installs ufw firewall and sets its rules on the web server.

sudo apt install -y ufw
sudo ufw enable
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw reload
