#!/usr/bin/env bash
# This script installs apache on a docker container and returns a page on request.

echo "Holberton School" > /var/www/html/index.html
systemctl apache2 status
systemctl apache2 start
