#!/usr/bin/env bash
# This script installs apache on a docker container and returns a page

docker exec -it b72a2d2da5b2 /bin/bash
apt-get update
apt-get install -y apache2
service apache start
echo "<html><body><h1>Hello Holberton</h1></body></html>" > /var/www/html/index.html
exit
